///<reference path="./../src/script/reference.d.ts"/>
///<reference path="./../ts-definitions/jasmine/jasmine.d.ts"/>
///<reference path="./../ts-definitions/angularjs/angular-mocks.d.ts"/>
///<reference path="./../ts-definitions/angularjs/angular-scenario.d.ts"/>
declare module "script/controller/product/ListProductController" { export = any }
declare module "script/service/mock/AlertServiceMock" { export = any }
declare module "script/service/mock/ProductServiceMock" { export = any }
declare module "script/service/mock/UserServiceMock" { export = any }
declare module "script/service/mock/AuthServiceMock" { export = any }
declare module "script/service/mock/base/EntityServiceMock" { export = any }
declare module "script/service/impl/NavigationServiceImpl" { export = any }
declare module "script/modularity/ControllerModule" { export = any }